### ISSUE TITLE
Migration Guide to Percolator

### ISSUE THREAD

**Issue by typeparameter** [purduecsbridge/barista#18]
We have recently created a new grading framework, [Percolator](https://github.com/purduecsbridge/percolator), to replace Barista. While the Barista library will still be hosted here and deployed on GitHub Packages for the time being, we strongly recommend migrating to Percolator if possible, as it will no longer receive updates.

### `GradescopeGrader` is replaced by `AutoGrader`
Rather than use `GradescopeGrader`, you can use `AutoGrader` to grade test cases.

Before:
```java
Class<?>[] testSuites = {UsernameGeneratorTest.class};
GradescopeGrader.run(testSuites, 100.0);
```

After:
```java
Class<?>[] testSuites = {UsernameGeneratorTest.class};
AutoGrader.grade(testSuites)
    .withMaxScore(100.0)
    .run();
```

### `TestCase` `number` parameter is now `group`
The optional `number` parameter is now `group`.

Before:
```java
@Test
@TestCase(name = "Test 1", number = "Class 1")
public void testCaseOne() { ... }
```

After:
```java
@Test
@TestCase(name = "Test 1", group = "Class 1")
public void testCaseOne() { ... }
```

### `WeightCalc` has been removed
The `WeightCalc` class is no longer necessary and has been removed. This is because test case point scaling is done automatically.

### `TestSuite` has been removed
The `TestSuite` annotation is no longer necessary and has been removed.

### `TestError` is replaced by `util.DebugUtilities`
The `TestError` class and its methods have been replaced by the `DebugUtilities` class. `TestError.unexpectedError` can be replicated by using `DebugUtilities.failWithoutCause`, and `TestError.studentError` can be replicated by using `DebugUtilities.failWithStackTrace`.

## Additional Information

[API documentation](https://purduecsbridge.github.io/percolator/api/) is available to review. Details on new additions will be given in the [release notes](https://github.com/purduecsbridge/percolator/packages/513132).

**Comment by drewdavis21** [comment]
Update: Added DebugUtilities as drop-in replacement for TestError.
